### ISSUE TITLE
Add source generator for handling global using directives.

### ISSUE THREAD

**Issue by tacosontitan** [tacosontitan/Hussy.Net#8]
The `Hussy.Net.Terminal` project is a great way for golfers to test their snippets, but deploying `Hussy.Net` as a NuGet package allows them to set up a project locally for their snippets. Ideally, the package would be friendly to that scenario and make it where consumers do not have to define the global using directives themselves.

The current expected output for this would be:

```cs
global using Hussy.Net;
global using static Hussy.Net.Hussy;
```

The source generator should be in it's own project `Hussy.Net.Generators`.

**Comment by viceroypenguin** [comment]
This can be done simpler than a source generator by doing the following:
```xml
<!-- Hussy.Net.csproj -->
<Content Include="Hussy.props">
      <Pack>true</Pack>
      <PackagePath>build\</PackagePath>
</Content>
```

```xml
<!-- Hussy.props -->
<ItemGroup>
  <Usings Include="Hussy.Net" />
  <Usings Include="Hussy.Net.Hussy" Static="true" />
</ItemGroup>
```
